const fs = require('fs');
const p = 'd:/Github/Stephen/Frontend/src/App.tsx';
let c = fs.readFileSync(p, 'utf8');

// 1. Add state variable
c = c.replace(/  const \[currentUserRole, setCurrentUserRole\] = useState<'client' \| 'provider' \| 'supervisor' \| 'hr' \| 'finance' \| 'admin' \| null>\(null\);\r?\n/,
`  const [currentUserRole, setCurrentUserRole] = useState<'client' | 'provider' | 'supervisor' | 'hr' | 'finance' | 'admin' | null>(null);\n  const [providerVerificationStatus, setProviderVerificationStatus] = useState<'pending' | 'active' | 'rejected' | null>(null);\n`);

// 2. Fix session restore (login/refresh)
c = c.replace(/            \} else if \(role === 'provider'\) \{\r?\n              setCurrentUserRole\('provider'\);\r?\n              if \(user\.verification_status === 'pending'\) \{/,
`            } else if (role === 'provider') {\n              setCurrentUserRole('provider');\n              setProviderVerificationStatus(user.verification_status || 'pending');\n              if (user.verification_status === 'pending') {`);

// 3. Fix handleSignupSubmit
c = c.replace(/      \} else if \(role === 'provider'\) \{\r?\n        setCurrentUserRole\('provider'\);\r?\n        setCurrentPage\('providerPendingVerification'\);\r?\n      \}/,
`      } else if (role === 'provider') {\n        setCurrentUserRole('provider');\n        setProviderVerificationStatus(user.verification_status || 'pending');\n        setCurrentPage('providerPendingVerification');\n      }`);

// 4. Fix handleLoginSubmit
c = c.replace(/      \} else if \(role === 'provider'\) \{\r?\n        setCurrentUserRole\('provider'\);\r?\n        if \(user\.verification_status === 'pending'\) \{/,
`      } else if (role === 'provider') {\n        setCurrentUserRole('provider');\n        setProviderVerificationStatus(user.verification_status || 'pending');\n        if (user.verification_status === 'pending') {`);

// 5. Fix navigateToDashboard
c = c.replace(/    \} else if \(currentUserRole === 'provider'\) \{\r?\n      setCurrentPage\('providerDashboard'\);\r?\n    \} else if \(currentUserRole === 'supervisor'\) \{/, 
`    } else if (currentUserRole === 'provider') {\n      if (providerVerificationStatus === 'active') {\n        setCurrentPage('providerDashboard');\n      } else {\n        setCurrentPage('providerPendingVerification');\n      }\n    } else if (currentUserRole === 'supervisor') {`);

// 6. Fix Header menu logic
c = c.replace(/                \{currentUserRole === 'provider' && \(/, 
`                {currentUserRole === 'provider' && providerVerificationStatus === 'active' && (`);

c = c.replace(/                        <button \r?\n                          onClick=\{\(\) => \{\r?\n                            navigateToDashboard\(\);\r?\n                            setIsProfileMenuOpen\(false\);\r?\n                          \}\}\r?\n                          className=\"flex items-center gap-3 px-3 py-2 rounded-xl text-slate-700 hover:bg-indigo-50 hover:text-indigo-700 font-medium transition-colors text-sm w-full text-left\"\r?\n                        >\r?\n                          <LayoutDashboard className=\"w-4 h-4\" \/>\r?\n                          Dashboard\r?\n                        <\/button>\r?\n                        <button \r?\n                          onClick=\{\(\) => \{\r?\n                            setCurrentPage\('userProfile'\);\r?\n                            setIsProfileMenuOpen\(false\);\r?\n                          \}\}\r?\n                          className=\"flex items-center gap-3 px-3 py-2 rounded-xl text-slate-700 hover:bg-indigo-50 hover:text-indigo-700 font-medium transition-colors text-sm w-full text-left\"\r?\n                        >\r?\n                          <User className=\"w-4 h-4\" \/>\r?\n                          User Profile\r?\n                        <\/button>\r?\n                        <button \r?\n                          onClick=\{\(\) => \{\r?\n                            setCurrentPage\('settings'\);\r?\n                            setIsProfileMenuOpen\(false\);\r?\n                          \}\}\r?\n                          className=\"flex items-center gap-3 px-3 py-2 rounded-xl text-slate-600 hover:bg-slate-50 hover:text-slate-900 font-medium transition-colors text-sm w-full text-left\"\r?\n                        >\r?\n                          <Settings className=\"w-4 h-4\" \/>\r?\n                          Settings\r?\n                        <\/button>/, 
`                        {(currentUserRole !== 'provider' || providerVerificationStatus === 'active') && (\n                          <>\n                            <button \n                              onClick={() => {\n                                navigateToDashboard();\n                                setIsProfileMenuOpen(false);\n                              }}\n                              className=\"flex items-center gap-3 px-3 py-2 rounded-xl text-slate-700 hover:bg-indigo-50 hover:text-indigo-700 font-medium transition-colors text-sm w-full text-left\"\n                            >\n                              <LayoutDashboard className=\"w-4 h-4\" />\n                              Dashboard\n                            </button>\n                            <button \n                              onClick={() => {\n                                setCurrentPage('userProfile');\n                                setIsProfileMenuOpen(false);\n                              }}\n                              className=\"flex items-center gap-3 px-3 py-2 rounded-xl text-slate-700 hover:bg-indigo-50 hover:text-indigo-700 font-medium transition-colors text-sm w-full text-left\"\n                            >\n                              <User className=\"w-4 h-4\" />\n                              User Profile\n                            </button>\n                            <button \n                              onClick={() => {\n                                setCurrentPage('settings');\n                                setIsProfileMenuOpen(false);\n                              }}\n                              className=\"flex items-center gap-3 px-3 py-2 rounded-xl text-slate-600 hover:bg-slate-50 hover:text-slate-900 font-medium transition-colors text-sm w-full text-left\"\n                            >\n                              <Settings className=\"w-4 h-4\" />\n                              Settings\n                            </button>\n                          </>\n                        )}`);

// 7. Fix Hourly Rate in state
c = c.replace(/bio: user\.bio \|\| '',\r?\n\s*avatar:/g, `bio: user.bio || '',\n                hourlyRate: user.provider_profile?.hourly_rate || 1500,\n                avatar:`);
c = c.replace(/bio: updatedUser\.bio \|\| '',\r?\n\s*avatar:/g, `bio: updatedUser.bio || '',\n                hourlyRate: updatedUser.provider_profile?.hourly_rate || 1500,\n                avatar:`);
c = c.replace(/bio: '',\r?\n\s*avatar: '',/g, `bio: '',\n          hourlyRate: '',\n          avatar: '',`);

// 8. Fix Hourly Rate in form
c = c.replace(/                  \{\/\* Bio \*\/\}\r?\n                  <div>\r?\n                    <label className=\"block text-sm font-medium text-slate-700 mb-1\.5\">Bio<\/label>\r?\n                    \{isEditingProfile \? \(\r?\n                      <textarea \r?\n                        value=\{profileData\.bio\}\r?\n                        onChange=\{\(e\) => setProfileData\(\{\.\.\.profileData, bio: e\.target\.value\}\)\}\r?\n                        rows=\{4\}\r?\n                        className=\"w-full px-4 py-3 bg-white\/70 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500\/50 text-slate-900 transition-all text-sm resize-none\"\r?\n                      \/>\r?\n                    \) : \(\r?\n                      <p className=\"px-4 py-3 bg-slate-50\/50 border border-transparent rounded-xl text-slate-600 text-sm leading-relaxed min-h-\[100px\]\">\r?\n                        \{profileData\.bio \|\| 'No bio provided yet\.'\}\r?\n                      <\/p>\r?\n                    \}\r?\n                  <\/div>/, 
`                  {/* Bio */}\n                  <div>\n                    <label className=\"block text-sm font-medium text-slate-700 mb-1.5\">Bio</label>\n                    {isEditingProfile ? (\n                      <textarea \n                        value={profileData.bio}\n                        onChange={(e) => setProfileData({...profileData, bio: e.target.value})}\n                        rows={4}\n                        className=\"w-full px-4 py-3 bg-white/70 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500/50 text-slate-900 transition-all text-sm resize-none\"\n                      />\n                    ) : (\n                      <p className=\"px-4 py-3 bg-slate-50/50 border border-transparent rounded-xl text-slate-600 text-sm leading-relaxed min-h-[100px]\">\n                        {profileData.bio || 'No bio provided yet.'}\n                      </p>\n                    )}\n                  </div>\n\n                  {currentUserRole === 'provider' && (\n                    <div className=\"mt-6 pt-6 border-t border-slate-100\">\n                      <label className=\"block text-sm font-medium text-slate-700 mb-1.5\">Hourly Rate (LKR)</label>\n                      {isEditingProfile ? (\n                        <input \n                          type=\"number\" \n                          value={profileData.hourlyRate}\n                          onChange={(e) => setProfileData({...profileData, hourlyRate: e.target.value})}\n                          className=\"w-full px-4 py-2.5 bg-white/70 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500/50 text-slate-900 transition-all text-sm\"\n                        />\n                      ) : (\n                        <p className=\"px-4 py-2.5 bg-slate-50/50 border border-transparent rounded-xl text-slate-600 text-sm flex items-center h-11\">\n                          LKR {profileData.hourlyRate || 1500}/hr\n                        </p>\n                      )}\n                    </div>\n                  )}`);

// 9. Fix handleSaveProfile form appending
c = c.replace(/          formData\.append\('address', profileData\.location \|\| ''\);\r?\n          if \(profileAvatarFile\) \{/,
`          formData.append('address', profileData.location || '');\n          if (currentUserRole === 'provider') {\n            formData.append('hourly_rate', profileData.hourlyRate || '1500');\n          }\n          if (profileAvatarFile) {`);

fs.writeFileSync(p, c);
