const fs = require('fs');
const p = 'd:/Github/Stephen/Frontend/src/App.tsx';
let c = fs.readFileSync(p, 'utf8');

// 1. Remove Switch Terminal from HR Dashboard
c = c.replace(/              \{\/\* Quick Platform Switcher Footer \*\/\}\r?\n              <div className="p-4 border-t border-slate-800 bg-slate-950\/50">\r?\n                <p className="text-\[11px\] font-bold text-slate-500 uppercase tracking-wider mb-2">Switch Terminal<\/p>\r?\n                <div className="grid grid-cols-3 gap-1">\r?\n                  <button \r?\n                    onClick=\{\(\) => setCurrentPage\('adminDashboard'\)\}\r?\n                    className="px-2 py-1\.5 bg-slate-900 hover:bg-indigo-950 text-slate-300 hover:text-indigo-300 text-xs font-semibold rounded-lg border border-slate-800 transition-colors cursor-pointer"\r?\n                  >\r?\n                    Admin\r?\n                  <\/button>\r?\n                  <button \r?\n                    onClick=\{\(\) => setCurrentPage\('financeDashboard'\)\}\r?\n                    className="px-2 py-1\.5 bg-slate-900 hover:bg-indigo-950 text-slate-300 hover:text-indigo-300 text-xs font-semibold rounded-lg border border-slate-800 transition-colors cursor-pointer"\r?\n                  >\r?\n                    Finance\r?\n                  <\/button>\r?\n                  <button \r?\n                    onClick=\{\(\) => setCurrentPage\('supervisorDashboard'\)\}\r?\n                    className="px-2 py-1\.5 bg-slate-900 hover:bg-indigo-950 text-slate-300 hover:text-indigo-300 text-xs font-semibold rounded-lg border border-slate-800 transition-colors cursor-pointer"\r?\n                  >\r?\n                    Field\r?\n                  <\/button>\r?\n                <\/div>\r?\n              <\/div>/g, '');

// 2. Remove Switch Terminal from Finance Dashboard
c = c.replace(/              \{\/\* Quick Platform Switcher Footer \*\/\}\r?\n              <div className="p-4 border-t border-slate-800 bg-slate-950\/50">\r?\n                <p className="text-\[11px\] font-bold text-slate-500 uppercase tracking-wider mb-2">Switch Terminal<\/p>\r?\n                <div className="grid grid-cols-3 gap-1">\r?\n                  <button \r?\n                    onClick=\{\(\) => setCurrentPage\('adminDashboard'\)\}\r?\n                    className="px-2 py-1\.5 bg-slate-900 hover:bg-indigo-950 text-slate-300 hover:text-indigo-300 text-xs font-semibold rounded-lg border border-slate-800 transition-colors cursor-pointer"\r?\n                  >\r?\n                    Admin\r?\n                  <\/button>\r?\n                  <button \r?\n                    onClick=\{\(\) => setCurrentPage\('hrDashboard'\)\}\r?\n                    className="px-2 py-1\.5 bg-slate-900 hover:bg-indigo-950 text-slate-300 hover:text-indigo-300 text-xs font-semibold rounded-lg border border-slate-800 transition-colors cursor-pointer"\r?\n                  >\r?\n                    HR\r?\n                  <\/button>\r?\n                  <button \r?\n                    onClick=\{\(\) => setCurrentPage\('supervisorDashboard'\)\}\r?\n                    className="px-2 py-1\.5 bg-slate-900 hover:bg-indigo-950 text-slate-300 hover:text-indigo-300 text-xs font-semibold rounded-lg border border-slate-800 transition-colors cursor-pointer"\r?\n                  >\r?\n                    Field\r?\n                  <\/button>\r?\n                <\/div>\r?\n              <\/div>/g, '');

// 3. Hide Danger Zone for non-clients and non-providers
c = c.replace(/                \{\/\* Danger Zone \*\/\}\r?\n                <div className="pt-4">\r?\n                  <h2 className="text-sm font-bold text-red-600 mb-4 uppercase tracking-wider">Danger Zone<\/h2>/,
`                {/* Danger Zone */}\n                {['client', 'provider'].includes(currentUserRole || '') && (\n                <div className=\"pt-4\">\n                  <h2 className=\"text-sm font-bold text-red-600 mb-4 uppercase tracking-wider\">Danger Zone</h2>`);

c = c.replace(/                      Deactivate\r?\n                    <\/button>\r?\n                  <\/div>\r?\n                <\/div>\r?\n              <\/div>\r?\n            <\/GlassCard>/,
`                      Deactivate\n                    </button>\n                  </div>\n                </div>\n                )}\n              </div>\n            </GlassCard>`);

fs.writeFileSync(p, c);
